#!/usr/bin/env bash
# Fizz buzz test again

x=1
while [ $x -le 100 ]
do
    if [ $(( x%3 )) -eq 0 -a $(( x%5 )) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $(( x%5 )) -eq 0 ]
    then
        echo "Buzz"
    elif [ $(( x%3 )) -eq 0 ]
    then
        echo "Fizz"
    else
        echo "$x"
    fi
    (( x++ ))
done
