#!/usr/bin/env bash
# Displays numbers from 1-20 using case statements

x=1
while [ $x -le 20 ]
do
    echo "$x"
    case $x in
      4)
        echo "bad luck from China"
	;;
      9)
        echo "bad luck from Japan"
	;;
      17)
        echo "bad luck from Italy"
	;;
    esac
    (( x++ ))
done
