#!/usr/bin/env bash
# lets play with time but still respect it

hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    mins=1
    while [ $mins -lt 60 ]
    do
      echo "$mins"
      (( mins++ ))
    done
    (( hour++ ))
done
