#!/usr/bin/env bash
# updates IP address in /etc/hosts
cp /etc/hosts ~/hosts.update
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.update
sed -i '2i8.8.8.8 facebook.com' ~/hosts.update
cp -f ~/hosts.update /etc/hosts
